spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=currency_db;encrypt=true;trustServerCertificate=true
    username: sa
    password: 1QAZ2WSX3EDc4@
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
server:
  port: 8080
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true