server:
  port: 8080

spring:
  application:
    name: weather-api

    weather: #api key放在yml方便維護，無須每次都改寫程式
  api:
    key: "3c1535f5d389f81e4f084d6712d5e572"
    base-url: "https://api.openweathermap.org/data/2.5"