version: '3.8'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: usermanagement-mssql
    restart: always
    ports:
      - "1433:1433"  # ✅ 使用 MSSQL 預設 Port
    environment:
      SA_PASSWORD: "1QAZ2WSX3EDc4@"  # ✅ 設定 MSSQL 管理員密碼（至少 8 碼，含大小寫 + 數字）
      ACCEPT_EULA: "Y"  # ✅ 接受 SQL Server 授權協議
      MSSQL_PID: "Express"  # ✅ 使用免費的 Express 版本
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data:
