spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=userid;encrypt=false
    username: sa
    password: 1QAZ2WSX3EDc4@
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

mybatis:
  configuration:
    map-underscore-to-camel-case: true