spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=atm_db;encrypt=false
    username: sa
    password: 1QAZ2WSX3EDc4@
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.SQLServerDialect
    show-sql: true
    ddl-auto: update
mybatis:
  configuration:
    map-underscore-to-camel-case: true