server:
  port: 8080

moneychangeapi:
  # api-url: "https://api.freecurrencyapi.com/v1"
  api-url: "https://openexchangerates.org/api"
  # api-key: "fca_live_RNZT1IxqlN5F0qnROpZk2SfjmLlXGIWHTB6Gw5Y8"
  api-key: "99bb96eec8f4452e9ba3dc2dcc86f052"
  connect-timeout: 5000
  read-timeout: 5000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
