spring:
  scheduler:
    cron: "*/5 * * * * *" # 每 5 秒執行
  webclient:
    api-url: "http://localhost:8081/api/employee-data"
    timeout: 3s # 3 秒超時
# spring:
#   application:
#     name: training-bch-scheduler

#   scheduler:
#     interval: 5s
#     api:
#       url: "http://localhost:8081/api/data/extract"
#       timeout: 3s
#       timeout-message: "回覆時間過長，請稍後再試！"